name: RES Pipeline

on:
  workflow_dispatch:

jobs:
  lint_flow:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: yarn install --frozen-lockfile

    - run: yarn flow check --show-all-errors
    - run: yarn eslint
    - run: yarn stylelint
    - run: yarn i18n-lint

  build_deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: '22'
    - run: yarn install --frozen-lockfile
    - run: yarn build --browsers=all

    # Upload Firefox ZIP artifact
    - name: Upload Firefox ZIP
      uses: actions/upload-artifact@v4
      with:
        name: firefox-zip
        path: dist/zip/firefox.zip

